
name: Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: lissy93/dashy

    steps:
      - uses: actions/checkout@v2

      - name: Run Hello World
        run: echo Hello World!

      - name: Run install
        run: yarn install      
        
      - name: Run build
        run: yarn build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ftp.lucasbaccan.com.br
          FTP_USERNAME: github-matera-dashy@lucasbaccan.com.br
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: ./dist/
          REMOTE_DIR: ./
          ARGS: --verbose	--delete