
name: Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: lissy93/dashy

    steps:
      - uses: actions/checkout@v2

      - name: Run Hello World
        run: echo Hello World!

      - name: Run install
        run: yarn install      
        
      - name: Run build
        run: yarn build
